In [2]:
                                        # “Out of your vulnerabilities will come your strength.” ― Sigmund Freud

#Pandas is built on top of Numpy.
#Data labels and descriptive indices.
#Robust handling of common data formats and missing data.
#Relational database opeartion.
#Pandas series can hold a variety of object as its data point. 

In [3]:
#Pandas Series
#-->1.Making series object from python lists and dicts.
#-->2.extracting indexes and values.
#-->3.Indexing series objects implicitily and explicitily.

In [8]:
import pandas as pd

In [9]:
#Making Pandas series from simple python list

s=pd.Series([0,1,2,3,4,5],name='squares')
s

0    0
1    1
2    2
3    3
4    4
5    5
Name: squares, dtype: int64

In [70]:
#Extracting values

s.values

array([0, 1, 2, 3, 4, 5], dtype=int64)

In [71]:
#index given implicitily

s.index

RangeIndex(start=0, stop=6, step=1)

In [72]:
print(s[0])
print(s[2:4])

0
2    2
3    3
Name: squares, dtype: int64


In [73]:
pop2014=pd.Series([100,99.3,95.3,93.5,92.4,84.8,85.6,78.9,74.3,72.8],
                  index=['java','c','c++','python','c#','php','javascript','Ruby','R','Matlab'])

In [74]:
pop2014

java          100.0
c              99.3
c++            95.3
python         93.5
c#             92.4
php            84.8
javascript     85.6
Ruby           78.9
R              74.3
Matlab         72.8
dtype: float64

In [75]:
pop2014.index

Index([u'java', u'c', u'c++', u'python', u'c#', u'php', u'javascript', u'Ruby',
       u'R', u'Matlab'],
      dtype='object')

In [76]:
pop2014.values

array([ 100. ,   99.3,   95.3,   93.5,   92.4,   84.8,   85.6,   78.9,
         74.3,   72.8])

In [77]:
pop2014[0]
pop2014[0:2]
pop2014['python']

93.5

In [78]:

pop2014['c++':'c#']

c++       95.3
python    93.5
c#        92.4
dtype: float64

In [79]:
#iloc object using numbers

pop2014.iloc[0:2]

java    100.0
c        99.3
dtype: float64

In [80]:
#iloc object to make it clear u are using explicit values

pop2014.loc[:'Ruby']

java          100.0
c              99.3
c++            95.3
python         93.5
c#             92.4
php            84.8
javascript     85.6
Ruby           78.9
dtype: float64

In [81]:
#Making Series from Dictionary

pop2015=pd.Series({'java':100,'c':99.3,'c++':95.3,'python':93.5,'c#':92.4,'php':84.8,'javascript':85.6,'Ruby':78.9,'R':74.3,
                   'Matlab':72.8})

In [82]:
pop2015

Matlab         72.8
R              74.3
Ruby           78.9
c              99.3
c#             92.4
c++            95.3
java          100.0
javascript     85.6
php            84.8
python         93.5
dtype: float64

In [83]:
import numpy as np
import pandas as pd

labels=['a','b','c']
my_data=[10,20,30]

arr=np.array(my_data)
arr

array([10, 20, 30])

In [84]:
#Making a series taking list as input not passing any index it will take default index(numeric)

labels=['a','b','c']
my_data=[10,20,30]
pd.Series(data=my_data)

0    10
1    20
2    30
dtype: int64

In [85]:
#Making a series taking list as input and also passing Index.

labels=['a','b','c']
my_data=[10,20,30]
pd.Series(my_data,index=labels)

a    10
b    20
c    30
dtype: int64

In [86]:
#Making a List using a Dictionary

d={'a':10,'b':20,'c':30}
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [87]:
ser1=pd.Series([1,2,3,4],['USA','UK','JAPAN','india'])
ser1

USA      1
UK       2
JAPAN    3
india    4
dtype: int64

In [88]:
ser1['USA']

1

In [89]:
ser2=pd.Series([1,2,5,4],['USA','GERMANY','ITALY','JAPAN'])

In [90]:

ser2

USA        1
GERMANY    2
ITALY      5
JAPAN      4
dtype: int64

In [91]:
ser3=pd.Series(data=labels)
ser3

0    a
1    b
2    c
dtype: object

In [92]:
#If any operation then int converted into float(to retain all info)
#if labels is not there in both then O/P will be NAN otherwise if available in both it will be sum.

ser1+ser2

GERMANY    NaN
ITALY      NaN
JAPAN      7.0
UK         NaN
USA        2.0
india      NaN
dtype: float64

In [1]:
#Series Recaps

In [38]:
#Making Series

import pandas as pd

object=pd.Series([3,6,9,12,15])
print(object)
print(type(object))

0     3
1     6
2     9
3    12
4    15
dtype: int64
<class 'pandas.core.series.Series'>


In [39]:
#Getting index from series

object.index

RangeIndex(start=0, stop=5, step=1)

In [40]:
#Making country as Index

ww1_cas=pd.Series([8700000,4300000,3000000,2100000,400000],index=['USSR','Germany','china','japan','USA'])
ww1_cas

USSR       8700000
Germany    4300000
china      3000000
japan      2100000
USA         400000
dtype: int64

In [43]:
#Fetching value based on Index

ww1_cas['USA']

400000

In [47]:
#Check which country has casuality greater then 4 mill

ww1_cas[ww1_cas > 4000000]

USSR       8700000
Germany    4300000
dtype: int64

In [71]:
#Checking element available in series or not.

'USSR' in ww1_cas

True

In [72]:
#Converting series into a dictionary

ww1_dict=ww1_cas.to_dict()
ww1_dict

{'Germany': 4300000,
 'USA': 400000,
 'USSR': 8700000,
 'china': 3000000,
 'japan': 2100000}

In [73]:
#Converting back into a series

ww1_series=pd.Series(ww1_dict)
ww1_series

Germany    4300000
USA         400000
USSR       8700000
china      3000000
japan      2100000
dtype: int64

In [74]:
countries=['china','Germany','Japan','USA','USSR','Argentina']

In [75]:
obj2=pd.Series(ww1_dict,index=countries)

In [76]:
obj2

china        3000000.0
Germany      4300000.0
Japan              NaN
USA           400000.0
USSR         8700000.0
Argentina          NaN
dtype: float64

In [77]:
pd.isnull(obj2)

china        False
Germany      False
Japan         True
USA          False
USSR         False
Argentina     True
dtype: bool

In [78]:
pd.notnull(obj2)

china         True
Germany       True
Japan        False
USA           True
USSR          True
Argentina    False
dtype: bool

In [83]:
ww1_series

Germany    4300000
USA         400000
USSR       8700000
china      3000000
japan      2100000
dtype: int64

In [80]:
ww1_series + obj2

Argentina           NaN
Germany       8600000.0
Japan               NaN
USA            800000.0
USSR         17400000.0
china         6000000.0
japan               NaN
dtype: float64

In [81]:
obj2.name="world war 1 Casulaities"
obj2

china        3000000.0
Germany      4300000.0
Japan              NaN
USA           400000.0
USSR         8700000.0
Argentina          NaN
Name: world war 1 Casulaities, dtype: float64

In [82]:
obj2.index.name='countries'

In [70]:
obj2

countries
china        3000000.0
Germany      4300000.0
Japan              NaN
USA           400000.0
USSR         8700000.0
Argentina          NaN
Name: world war 1 Casulaities, dtype: float64